version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: agency_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      DB_NAME: agency_onboarding
      DB_USER: agency_user
      DB_PASSWORD: agency_password123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - agency_network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootpassword123",
        ]
      timeout: 10s
      retries: 10
      interval: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agency_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=agency_user
      - DB_PASSWORD=agency_password123
      - DB_NAME=agency_onboarding
      - DB_PORT=3306
      - PORT=3000
    volumes:
      - ./uploads:/usr/src/app/uploads
    networks:
      - agency_network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local

networks:
  agency_network:
    driver: bridge
